input {
  file {
    path => "/var/www/storage/logs/trace/*.log"   # logs journaliers
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "laravel-logs"
  }
}
